services:
  agent:
    image: ngrinder/agent:latest
    container_name: agent
    restart: always
    hostname: agent
    # sysctls:
    #   - net.core.somaxconn=65000
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc:
        soft: 1024000
        hard: 1024000
      nofile:
        soft: 1024000
        hard: 1024000
    extra_hosts:
      - "controller:${CONTROLLER_IP}"
    volumes:
      - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
      - ./ngrinder-agent:/opt/ngrinder-agent
      #- ./ngrinder-data/agent.conf:/opt/ngrinder-agent/.ngrinder-agent/agent.conf
    network_mode: host
